package com.example.apple.orm.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.apple.orm.bean.dao.Car;
import com.example.apple.orm.bean.User;

import com.example.apple.orm.bean.dao.CarDao;
import com.example.apple.orm.bean.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig carDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CarDao carDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        carDaoConfig = daoConfigMap.get(CarDao.class).clone();
        carDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        carDao = new CarDao(carDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Car.class, carDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        carDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CarDao getCarDao() {
        return carDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
